# Generated by Django 4.1.7 on 2023-02-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=50, verbose_name='Категория')),
                ('sensor_type', models.CharField(default='', max_length=50, verbose_name='Тип датчика')),
                ('sensor_symbol', models.CharField(default='', max_length=50, verbose_name='Обозначение')),
                ('sensor_url', models.CharField(default='', max_length=50, verbose_name='Ссылка на сайт производителя')),
                ('sensor_price', models.CharField(default='', max_length=50, verbose_name='Цена')),
                ('sensor_in_stock', models.CharField(default='', max_length=50, verbose_name='Наличие')),
            ],
            options={
                'verbose_name': 'Перечень датчиков',
                'verbose_name_plural': 'Перечень датчиков',
            },
        ),
    ]
