# Generated by Django 4.1.7 on 2023-02-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='sensor_url',
            field=models.SlugField(default='', max_length=250, unique=True, verbose_name='Ссылка на сайт производителя'),
        ),
    ]
