# Generated by Django 4.1.7 on 2023-02-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sensors_sensor_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inductive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=30, verbose_name='Категория датчика')),
                ('type', models.CharField(default='', max_length=30, verbose_name='Тип датчика')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Обозначение датчика')),
                ('url', models.SlugField(default='', max_length=250, unique=True, verbose_name='Ссылка на сайт производителя')),
                ('url_img', models.SlugField(default='', max_length=250, unique=True, verbose_name='Ссылка на рисунок датчика')),
                ('price', models.FloatField(default='', verbose_name='Цена')),
                ('stock', models.CharField(default='', max_length=50, verbose_name='Срок отгрузки')),
                ('manufacturer', models.CharField(default='', max_length=20, verbose_name='Производитель')),
                ('flush', models.CharField(default='', max_length=20, verbose_name='Способ установки')),
                ('spec', models.CharField(default='', max_length=50, verbose_name='Применение')),
                ('housing', models.CharField(default='', max_length=50, verbose_name='Конструктивное исполнение корпуса')),
                ('connection', models.CharField(default='', max_length=50, verbose_name='Способ подключения')),
                ('size', models.CharField(default='', max_length=30, verbose_name='Способ подключения')),
                ('material', models.CharField(default='', max_length=20, verbose_name='Материал корпуса')),
                ('IP', models.CharField(default='', max_length=10, verbose_name='Степень защиты')),
                ('output_structure', models.CharField(default='', max_length=40, verbose_name='Cтруктура выходного сигнала')),
                ('voltage', models.CharField(default='', max_length=30, verbose_name='Напряжение')),
                ('output_type', models.CharField(default='', max_length=20, verbose_name='Тип контакта')),
                ('adjust', models.CharField(default='', max_length=20, verbose_name='Регулировка')),
                ('distance', models.FloatField(default='', verbose_name='Номинальное расстояние')),
                ('indicator', models.CharField(default='', max_length=20, verbose_name='Индикация')),
                ('temperature', models.CharField(default='', max_length=30, verbose_name='Температурный диапазон')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sensors',
            options={'ordering': ('sensor_symbol',), 'verbose_name': 'Перечень датчиков', 'verbose_name_plural': 'Перечень датчиков'},
        ),
    ]
