# Generated by Django 4.1.7 on 2023-02-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_inductive_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductive',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Обозначение датчика'),
        ),
        migrations.AlterField(
            model_name='inductive',
            name='url_img',
            field=models.SlugField(default='', max_length=250, verbose_name='Ссылка на рисунок датчика'),
        ),
    ]
