# Generated by Django 4.1.7 on 2023-03-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_inductive_ip_alter_inductive_adjust_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inductive',
            options={'verbose_name': 'База индуктивных датчиков', 'verbose_name_plural': 'База индуктивных датчиков'},
        ),
        migrations.AlterField(
            model_name='inductive',
            name='size',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Габарит датчика'),
        ),
    ]
